<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Hello, World!</name>
  <uuid>2de782b6-aa73-4e97-9fb5-6bf4652c70d5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is not empty
then
	set decision to "Hello, " + Input;
   ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
